# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T14:05:00+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field, RootModel, conint, constr


class ActivityId(RootModel[constr(min_length=1, max_length=256)]):
    root: constr(min_length=1, max_length=256)


class ActivityTaskTimeoutType(Enum):
    START_TO_CLOSE = 'START_TO_CLOSE'
    SCHEDULE_TO_START = 'SCHEDULE_TO_START'
    SCHEDULE_TO_CLOSE = 'SCHEDULE_TO_CLOSE'
    HEARTBEAT = 'HEARTBEAT'


class Arn(RootModel[constr(min_length=1, max_length=1600)]):
    root: constr(min_length=1, max_length=1600)


class CancelTimerFailedCause(Enum):
    TIMER_ID_UNKNOWN = 'TIMER_ID_UNKNOWN'
    OPERATION_NOT_PERMITTED = 'OPERATION_NOT_PERMITTED'


class CancelWorkflowExecutionFailedCause(Enum):
    UNHANDLED_DECISION = 'UNHANDLED_DECISION'
    OPERATION_NOT_PERMITTED = 'OPERATION_NOT_PERMITTED'


class Canceled(RootModel[bool]):
    root: bool


class CauseMessage(RootModel[constr(max_length=1728)]):
    root: constr(max_length=1728)


class ChildPolicy(Enum):
    TERMINATE = 'TERMINATE'
    REQUEST_CANCEL = 'REQUEST_CANCEL'
    ABANDON = 'ABANDON'


class CloseStatus(Enum):
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    CANCELED = 'CANCELED'
    TERMINATED = 'TERMINATED'
    CONTINUED_AS_NEW = 'CONTINUED_AS_NEW'
    TIMED_OUT = 'TIMED_OUT'


class CloseStatusFilter(BaseModel):
    status: CloseStatus


class CompleteWorkflowExecutionFailedCause(Enum):
    UNHANDLED_DECISION = 'UNHANDLED_DECISION'
    OPERATION_NOT_PERMITTED = 'OPERATION_NOT_PERMITTED'


class ContinueAsNewWorkflowExecutionFailedCause(Enum):
    UNHANDLED_DECISION = 'UNHANDLED_DECISION'
    WORKFLOW_TYPE_DEPRECATED = 'WORKFLOW_TYPE_DEPRECATED'
    WORKFLOW_TYPE_DOES_NOT_EXIST = 'WORKFLOW_TYPE_DOES_NOT_EXIST'
    DEFAULT_EXECUTION_START_TO_CLOSE_TIMEOUT_UNDEFINED = (
        'DEFAULT_EXECUTION_START_TO_CLOSE_TIMEOUT_UNDEFINED'
    )
    DEFAULT_TASK_START_TO_CLOSE_TIMEOUT_UNDEFINED = (
        'DEFAULT_TASK_START_TO_CLOSE_TIMEOUT_UNDEFINED'
    )
    DEFAULT_TASK_LIST_UNDEFINED = 'DEFAULT_TASK_LIST_UNDEFINED'
    DEFAULT_CHILD_POLICY_UNDEFINED = 'DEFAULT_CHILD_POLICY_UNDEFINED'
    CONTINUE_AS_NEW_WORKFLOW_EXECUTION_RATE_EXCEEDED = (
        'CONTINUE_AS_NEW_WORKFLOW_EXECUTION_RATE_EXCEEDED'
    )
    OPERATION_NOT_PERMITTED = 'OPERATION_NOT_PERMITTED'


class Count(RootModel[conint(ge=0)]):
    root: conint(ge=0)


class Data(RootModel[constr(max_length=32768)]):
    root: constr(max_length=32768)


class DecisionTaskTimeoutType(Enum):
    START_TO_CLOSE = 'START_TO_CLOSE'


class DecisionType(Enum):
    ScheduleActivityTask = 'ScheduleActivityTask'
    RequestCancelActivityTask = 'RequestCancelActivityTask'
    CompleteWorkflowExecution = 'CompleteWorkflowExecution'
    FailWorkflowExecution = 'FailWorkflowExecution'
    CancelWorkflowExecution = 'CancelWorkflowExecution'
    ContinueAsNewWorkflowExecution = 'ContinueAsNewWorkflowExecution'
    RecordMarker = 'RecordMarker'
    StartTimer = 'StartTimer'
    CancelTimer = 'CancelTimer'
    SignalExternalWorkflowExecution = 'SignalExternalWorkflowExecution'
    RequestCancelExternalWorkflowExecution = 'RequestCancelExternalWorkflowExecution'
    StartChildWorkflowExecution = 'StartChildWorkflowExecution'
    ScheduleLambdaFunction = 'ScheduleLambdaFunction'


class DefaultUndefinedFault(RootModel[Any]):
    root: Any


class Description(RootModel[constr(max_length=1024)]):
    root: constr(max_length=1024)


class DomainAlreadyExistsFault(RootModel[Any]):
    root: Any


class DomainDeprecatedFault(RootModel[Any]):
    root: Any


class DomainName(RootModel[constr(min_length=1, max_length=256)]):
    root: constr(min_length=1, max_length=256)


class DurationInDays(RootModel[constr(min_length=1, max_length=8)]):
    root: constr(min_length=1, max_length=8)


class DurationInSeconds(RootModel[constr(min_length=1, max_length=8)]):
    root: constr(min_length=1, max_length=8)


class DurationInSecondsOptional(RootModel[constr(max_length=8)]):
    root: constr(max_length=8)


class EventId(RootModel[int]):
    root: int


class EventType(Enum):
    WorkflowExecutionStarted = 'WorkflowExecutionStarted'
    WorkflowExecutionCancelRequested = 'WorkflowExecutionCancelRequested'
    WorkflowExecutionCompleted = 'WorkflowExecutionCompleted'
    CompleteWorkflowExecutionFailed = 'CompleteWorkflowExecutionFailed'
    WorkflowExecutionFailed = 'WorkflowExecutionFailed'
    FailWorkflowExecutionFailed = 'FailWorkflowExecutionFailed'
    WorkflowExecutionTimedOut = 'WorkflowExecutionTimedOut'
    WorkflowExecutionCanceled = 'WorkflowExecutionCanceled'
    CancelWorkflowExecutionFailed = 'CancelWorkflowExecutionFailed'
    WorkflowExecutionContinuedAsNew = 'WorkflowExecutionContinuedAsNew'
    ContinueAsNewWorkflowExecutionFailed = 'ContinueAsNewWorkflowExecutionFailed'
    WorkflowExecutionTerminated = 'WorkflowExecutionTerminated'
    DecisionTaskScheduled = 'DecisionTaskScheduled'
    DecisionTaskStarted = 'DecisionTaskStarted'
    DecisionTaskCompleted = 'DecisionTaskCompleted'
    DecisionTaskTimedOut = 'DecisionTaskTimedOut'
    ActivityTaskScheduled = 'ActivityTaskScheduled'
    ScheduleActivityTaskFailed = 'ScheduleActivityTaskFailed'
    ActivityTaskStarted = 'ActivityTaskStarted'
    ActivityTaskCompleted = 'ActivityTaskCompleted'
    ActivityTaskFailed = 'ActivityTaskFailed'
    ActivityTaskTimedOut = 'ActivityTaskTimedOut'
    ActivityTaskCanceled = 'ActivityTaskCanceled'
    ActivityTaskCancelRequested = 'ActivityTaskCancelRequested'
    RequestCancelActivityTaskFailed = 'RequestCancelActivityTaskFailed'
    WorkflowExecutionSignaled = 'WorkflowExecutionSignaled'
    MarkerRecorded = 'MarkerRecorded'
    RecordMarkerFailed = 'RecordMarkerFailed'
    TimerStarted = 'TimerStarted'
    StartTimerFailed = 'StartTimerFailed'
    TimerFired = 'TimerFired'
    TimerCanceled = 'TimerCanceled'
    CancelTimerFailed = 'CancelTimerFailed'
    StartChildWorkflowExecutionInitiated = 'StartChildWorkflowExecutionInitiated'
    StartChildWorkflowExecutionFailed = 'StartChildWorkflowExecutionFailed'
    ChildWorkflowExecutionStarted = 'ChildWorkflowExecutionStarted'
    ChildWorkflowExecutionCompleted = 'ChildWorkflowExecutionCompleted'
    ChildWorkflowExecutionFailed = 'ChildWorkflowExecutionFailed'
    ChildWorkflowExecutionTimedOut = 'ChildWorkflowExecutionTimedOut'
    ChildWorkflowExecutionCanceled = 'ChildWorkflowExecutionCanceled'
    ChildWorkflowExecutionTerminated = 'ChildWorkflowExecutionTerminated'
    SignalExternalWorkflowExecutionInitiated = (
        'SignalExternalWorkflowExecutionInitiated'
    )
    SignalExternalWorkflowExecutionFailed = 'SignalExternalWorkflowExecutionFailed'
    ExternalWorkflowExecutionSignaled = 'ExternalWorkflowExecutionSignaled'
    RequestCancelExternalWorkflowExecutionInitiated = (
        'RequestCancelExternalWorkflowExecutionInitiated'
    )
    RequestCancelExternalWorkflowExecutionFailed = (
        'RequestCancelExternalWorkflowExecutionFailed'
    )
    ExternalWorkflowExecutionCancelRequested = (
        'ExternalWorkflowExecutionCancelRequested'
    )
    LambdaFunctionScheduled = 'LambdaFunctionScheduled'
    LambdaFunctionStarted = 'LambdaFunctionStarted'
    LambdaFunctionCompleted = 'LambdaFunctionCompleted'
    LambdaFunctionFailed = 'LambdaFunctionFailed'
    LambdaFunctionTimedOut = 'LambdaFunctionTimedOut'
    ScheduleLambdaFunctionFailed = 'ScheduleLambdaFunctionFailed'
    StartLambdaFunctionFailed = 'StartLambdaFunctionFailed'


class ExecutionStatus(Enum):
    OPEN = 'OPEN'
    CLOSED = 'CLOSED'


class FailWorkflowExecutionFailedCause(Enum):
    UNHANDLED_DECISION = 'UNHANDLED_DECISION'
    OPERATION_NOT_PERMITTED = 'OPERATION_NOT_PERMITTED'


class FailWorkflowExecutionFailedEventAttributes(BaseModel):
    cause: FailWorkflowExecutionFailedCause
    decisionTaskCompletedEventId: EventId


class FailureReason(RootModel[constr(max_length=256)]):
    root: constr(max_length=256)


class FunctionId(RootModel[constr(min_length=1, max_length=256)]):
    root: constr(min_length=1, max_length=256)


class FunctionInput(RootModel[constr(min_length=0, max_length=32768)]):
    root: constr(min_length=0, max_length=32768)


class FunctionName(RootModel[constr(min_length=1, max_length=64)]):
    root: constr(min_length=1, max_length=64)


class Identity(RootModel[constr(max_length=256)]):
    root: constr(max_length=256)


class LambdaFunctionCompletedEventAttributes(BaseModel):
    result: Optional[Data] = None
    scheduledEventId: EventId
    startedEventId: EventId


class LambdaFunctionFailedEventAttributes(BaseModel):
    details: Optional[Data] = None
    reason: Optional[FailureReason] = None
    scheduledEventId: EventId
    startedEventId: EventId


class LambdaFunctionScheduledEventAttributes(BaseModel):
    control: Optional[Data] = None
    decisionTaskCompletedEventId: EventId
    id: FunctionId
    input: Optional[FunctionInput] = None
    name: FunctionName
    startToCloseTimeout: Optional[DurationInSecondsOptional] = None


class LambdaFunctionStartedEventAttributes(BaseModel):
    scheduledEventId: EventId


class LambdaFunctionTimeoutType(Enum):
    START_TO_CLOSE = 'START_TO_CLOSE'


class LimitExceededFault(RootModel[Any]):
    root: Any


class LimitedData(RootModel[constr(max_length=2048)]):
    root: constr(max_length=2048)


class ListTagsForResourceInput(BaseModel):
    resourceArn: Arn


class MarkerName(RootModel[constr(min_length=1, max_length=256)]):
    root: constr(min_length=1, max_length=256)


class MarkerRecordedEventAttributes(BaseModel):
    decisionTaskCompletedEventId: EventId
    details: Optional[Data] = None
    markerName: MarkerName


class Name(RootModel[constr(min_length=1, max_length=256)]):
    root: constr(min_length=1, max_length=256)


class OpenDecisionTasksCount(RootModel[conint(ge=0, le=1)]):
    root: conint(ge=0, le=1)


class OperationNotPermittedFault(RootModel[Any]):
    root: Any


class PageSize(RootModel[conint(ge=0, le=1000)]):
    root: conint(ge=0, le=1000)


class PageToken(RootModel[constr(max_length=2048)]):
    root: constr(max_length=2048)


class RecordMarkerDecisionAttributes(BaseModel):
    details: Optional[Data] = None
    markerName: MarkerName


class RecordMarkerFailedCause(Enum):
    OPERATION_NOT_PERMITTED = 'OPERATION_NOT_PERMITTED'


class RecordMarkerFailedEventAttributes(BaseModel):
    cause: RecordMarkerFailedCause
    decisionTaskCompletedEventId: EventId
    markerName: MarkerName


class RegistrationStatus(Enum):
    REGISTERED = 'REGISTERED'
    DEPRECATED = 'DEPRECATED'


class RequestCancelActivityTaskDecisionAttributes(BaseModel):
    activityId: ActivityId


class RequestCancelActivityTaskFailedCause(Enum):
    ACTIVITY_ID_UNKNOWN = 'ACTIVITY_ID_UNKNOWN'
    OPERATION_NOT_PERMITTED = 'OPERATION_NOT_PERMITTED'


class RequestCancelActivityTaskFailedEventAttributes(BaseModel):
    activityId: ActivityId
    cause: RequestCancelActivityTaskFailedCause
    decisionTaskCompletedEventId: EventId


class RequestCancelExternalWorkflowExecutionFailedCause(Enum):
    UNKNOWN_EXTERNAL_WORKFLOW_EXECUTION = 'UNKNOWN_EXTERNAL_WORKFLOW_EXECUTION'
    REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_RATE_EXCEEDED = (
        'REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_RATE_EXCEEDED'
    )
    OPERATION_NOT_PERMITTED = 'OPERATION_NOT_PERMITTED'


class ResourceTagKey(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class ResourceTagKeyList(RootModel[List[ResourceTagKey]]):
    root: List[ResourceTagKey]


class ResourceTagValue(RootModel[constr(max_length=256)]):
    root: constr(max_length=256)


class ReverseOrder(RootModel[bool]):
    root: bool


class ScheduleActivityTaskFailedCause(Enum):
    ACTIVITY_TYPE_DEPRECATED = 'ACTIVITY_TYPE_DEPRECATED'
    ACTIVITY_TYPE_DOES_NOT_EXIST = 'ACTIVITY_TYPE_DOES_NOT_EXIST'
    ACTIVITY_ID_ALREADY_IN_USE = 'ACTIVITY_ID_ALREADY_IN_USE'
    OPEN_ACTIVITIES_LIMIT_EXCEEDED = 'OPEN_ACTIVITIES_LIMIT_EXCEEDED'
    ACTIVITY_CREATION_RATE_EXCEEDED = 'ACTIVITY_CREATION_RATE_EXCEEDED'
    DEFAULT_SCHEDULE_TO_CLOSE_TIMEOUT_UNDEFINED = (
        'DEFAULT_SCHEDULE_TO_CLOSE_TIMEOUT_UNDEFINED'
    )
    DEFAULT_TASK_LIST_UNDEFINED = 'DEFAULT_TASK_LIST_UNDEFINED'
    DEFAULT_SCHEDULE_TO_START_TIMEOUT_UNDEFINED = (
        'DEFAULT_SCHEDULE_TO_START_TIMEOUT_UNDEFINED'
    )
    DEFAULT_START_TO_CLOSE_TIMEOUT_UNDEFINED = (
        'DEFAULT_START_TO_CLOSE_TIMEOUT_UNDEFINED'
    )
    DEFAULT_HEARTBEAT_TIMEOUT_UNDEFINED = 'DEFAULT_HEARTBEAT_TIMEOUT_UNDEFINED'
    OPERATION_NOT_PERMITTED = 'OPERATION_NOT_PERMITTED'


class ScheduleLambdaFunctionDecisionAttributes(BaseModel):
    control: Optional[Data] = None
    id: FunctionId
    input: Optional[FunctionInput] = None
    name: FunctionName
    startToCloseTimeout: Optional[DurationInSecondsOptional] = None


class ScheduleLambdaFunctionFailedCause(Enum):
    ID_ALREADY_IN_USE = 'ID_ALREADY_IN_USE'
    OPEN_LAMBDA_FUNCTIONS_LIMIT_EXCEEDED = 'OPEN_LAMBDA_FUNCTIONS_LIMIT_EXCEEDED'
    LAMBDA_FUNCTION_CREATION_RATE_EXCEEDED = 'LAMBDA_FUNCTION_CREATION_RATE_EXCEEDED'
    LAMBDA_SERVICE_NOT_AVAILABLE_IN_REGION = 'LAMBDA_SERVICE_NOT_AVAILABLE_IN_REGION'


class ScheduleLambdaFunctionFailedEventAttributes(BaseModel):
    cause: ScheduleLambdaFunctionFailedCause
    decisionTaskCompletedEventId: EventId
    id: FunctionId
    name: FunctionName


class SignalExternalWorkflowExecutionFailedCause(Enum):
    UNKNOWN_EXTERNAL_WORKFLOW_EXECUTION = 'UNKNOWN_EXTERNAL_WORKFLOW_EXECUTION'
    SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_RATE_EXCEEDED = (
        'SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_RATE_EXCEEDED'
    )
    OPERATION_NOT_PERMITTED = 'OPERATION_NOT_PERMITTED'


class SignalName(RootModel[constr(min_length=1, max_length=256)]):
    root: constr(min_length=1, max_length=256)


class StartChildWorkflowExecutionFailedCause(Enum):
    WORKFLOW_TYPE_DOES_NOT_EXIST = 'WORKFLOW_TYPE_DOES_NOT_EXIST'
    WORKFLOW_TYPE_DEPRECATED = 'WORKFLOW_TYPE_DEPRECATED'
    OPEN_CHILDREN_LIMIT_EXCEEDED = 'OPEN_CHILDREN_LIMIT_EXCEEDED'
    OPEN_WORKFLOWS_LIMIT_EXCEEDED = 'OPEN_WORKFLOWS_LIMIT_EXCEEDED'
    CHILD_CREATION_RATE_EXCEEDED = 'CHILD_CREATION_RATE_EXCEEDED'
    WORKFLOW_ALREADY_RUNNING = 'WORKFLOW_ALREADY_RUNNING'
    DEFAULT_EXECUTION_START_TO_CLOSE_TIMEOUT_UNDEFINED = (
        'DEFAULT_EXECUTION_START_TO_CLOSE_TIMEOUT_UNDEFINED'
    )
    DEFAULT_TASK_LIST_UNDEFINED = 'DEFAULT_TASK_LIST_UNDEFINED'
    DEFAULT_TASK_START_TO_CLOSE_TIMEOUT_UNDEFINED = (
        'DEFAULT_TASK_START_TO_CLOSE_TIMEOUT_UNDEFINED'
    )
    DEFAULT_CHILD_POLICY_UNDEFINED = 'DEFAULT_CHILD_POLICY_UNDEFINED'
    OPERATION_NOT_PERMITTED = 'OPERATION_NOT_PERMITTED'


class StartLambdaFunctionFailedCause(Enum):
    ASSUME_ROLE_FAILED = 'ASSUME_ROLE_FAILED'


class StartLambdaFunctionFailedEventAttributes(BaseModel):
    cause: Optional[StartLambdaFunctionFailedCause] = None
    message: Optional[CauseMessage] = None
    scheduledEventId: Optional[EventId] = None


class StartTimerFailedCause(Enum):
    TIMER_ID_ALREADY_IN_USE = 'TIMER_ID_ALREADY_IN_USE'
    OPEN_TIMERS_LIMIT_EXCEEDED = 'OPEN_TIMERS_LIMIT_EXCEEDED'
    TIMER_CREATION_RATE_EXCEEDED = 'TIMER_CREATION_RATE_EXCEEDED'
    OPERATION_NOT_PERMITTED = 'OPERATION_NOT_PERMITTED'


class Tag(RootModel[constr(min_length=0, max_length=256)]):
    root: constr(min_length=0, max_length=256)


class TagFilter(BaseModel):
    tag: Tag


class TagList(RootModel[List[Tag]]):
    root: List[Tag] = Field(..., max_length=5)


class TaskList(BaseModel):
    name: Name


class TaskPriority(RootModel[str]):
    root: str


class TaskToken(RootModel[constr(min_length=1, max_length=1024)]):
    root: constr(min_length=1, max_length=1024)


class TerminateReason(RootModel[constr(max_length=256)]):
    root: constr(max_length=256)


class TimerId(RootModel[constr(min_length=1, max_length=256)]):
    root: constr(min_length=1, max_length=256)


class TimerStartedEventAttributes(BaseModel):
    control: Optional[Data] = None
    decisionTaskCompletedEventId: EventId
    startToFireTimeout: DurationInSeconds
    timerId: TimerId


class Timestamp(RootModel[datetime]):
    root: datetime


class TooManyTagsFault(RootModel[Any]):
    root: Any


class Truncated(RootModel[bool]):
    root: bool


class TypeAlreadyExistsFault(RootModel[Any]):
    root: Any


class TypeDeprecatedFault(RootModel[Any]):
    root: Any


class UndeprecateDomainInput(BaseModel):
    name: DomainName


class UnknownResourceFault(RootModel[Any]):
    root: Any


class UntagResourceInput(BaseModel):
    resourceArn: Arn
    tagKeys: ResourceTagKeyList


class Version(RootModel[constr(min_length=1, max_length=64)]):
    root: constr(min_length=1, max_length=64)


class VersionOptional(RootModel[constr(max_length=64)]):
    root: constr(max_length=64)


class WorkflowExecutionAlreadyStartedFault(RootModel[Any]):
    root: Any


class WorkflowExecutionCancelRequestedCause(Enum):
    CHILD_POLICY_APPLIED = 'CHILD_POLICY_APPLIED'


class WorkflowExecutionCanceledEventAttributes(BaseModel):
    decisionTaskCompletedEventId: EventId
    details: Optional[Data] = None


class WorkflowExecutionCompletedEventAttributes(BaseModel):
    decisionTaskCompletedEventId: EventId
    result: Optional[Data] = None


class WorkflowExecutionConfiguration(BaseModel):
    childPolicy: ChildPolicy
    executionStartToCloseTimeout: DurationInSeconds
    lambdaRole: Optional[Arn] = None
    taskList: TaskList
    taskPriority: Optional[TaskPriority] = None
    taskStartToCloseTimeout: DurationInSeconds


class WorkflowExecutionCount(BaseModel):
    count: Count
    truncated: Optional[Truncated] = None


class WorkflowExecutionFailedEventAttributes(BaseModel):
    decisionTaskCompletedEventId: EventId
    details: Optional[Data] = None
    reason: Optional[FailureReason] = None


class WorkflowExecutionOpenCounts(BaseModel):
    openActivityTasks: Count
    openChildWorkflowExecutions: Count
    openDecisionTasks: OpenDecisionTasksCount
    openLambdaFunctions: Optional[Count] = None
    openTimers: Count


class WorkflowExecutionTerminatedCause(Enum):
    CHILD_POLICY_APPLIED = 'CHILD_POLICY_APPLIED'
    EVENT_LIMIT_EXCEEDED = 'EVENT_LIMIT_EXCEEDED'
    OPERATOR_INITIATED = 'OPERATOR_INITIATED'


class WorkflowExecutionTerminatedEventAttributes(BaseModel):
    cause: Optional[WorkflowExecutionTerminatedCause] = None
    childPolicy: ChildPolicy
    details: Optional[Data] = None
    reason: Optional[TerminateReason] = None


class WorkflowExecutionTimeoutType(Enum):
    START_TO_CLOSE = 'START_TO_CLOSE'


class WorkflowId(RootModel[constr(min_length=1, max_length=256)]):
    root: constr(min_length=1, max_length=256)


class WorkflowRunId(RootModel[constr(min_length=1, max_length=64)]):
    root: constr(min_length=1, max_length=64)


class WorkflowRunIdOptional(RootModel[constr(max_length=64)]):
    root: constr(max_length=64)


class WorkflowType(BaseModel):
    name: Name
    version: Version


class WorkflowTypeConfiguration(BaseModel):
    defaultChildPolicy: Optional[ChildPolicy] = None
    defaultExecutionStartToCloseTimeout: Optional[DurationInSecondsOptional] = None
    defaultLambdaRole: Optional[Arn] = None
    defaultTaskList: Optional[TaskList] = None
    defaultTaskPriority: Optional[TaskPriority] = None
    defaultTaskStartToCloseTimeout: Optional[DurationInSecondsOptional] = None


class WorkflowTypeFilter(BaseModel):
    name: Name
    version: Optional[VersionOptional] = None


class WorkflowTypeInfo(BaseModel):
    creationDate: Timestamp
    deprecationDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    status: RegistrationStatus
    workflowType: WorkflowType


class WorkflowTypeInfoList(RootModel[List[WorkflowTypeInfo]]):
    root: List[WorkflowTypeInfo]


class WorkflowTypeInfos(BaseModel):
    nextPageToken: Optional[PageToken] = None
    typeInfos: WorkflowTypeInfoList


class XAmzTarget(Enum):
    SimpleWorkflowService_CountClosedWorkflowExecutions = (
        'SimpleWorkflowService.CountClosedWorkflowExecutions'
    )


class XAmzTarget1(Enum):
    SimpleWorkflowService_CountOpenWorkflowExecutions = (
        'SimpleWorkflowService.CountOpenWorkflowExecutions'
    )


class XAmzTarget2(Enum):
    SimpleWorkflowService_CountPendingActivityTasks = (
        'SimpleWorkflowService.CountPendingActivityTasks'
    )


class XAmzTarget3(Enum):
    SimpleWorkflowService_CountPendingDecisionTasks = (
        'SimpleWorkflowService.CountPendingDecisionTasks'
    )


class XAmzTarget4(Enum):
    SimpleWorkflowService_DeprecateActivityType = (
        'SimpleWorkflowService.DeprecateActivityType'
    )


class XAmzTarget5(Enum):
    SimpleWorkflowService_DeprecateDomain = 'SimpleWorkflowService.DeprecateDomain'


class XAmzTarget6(Enum):
    SimpleWorkflowService_DeprecateWorkflowType = (
        'SimpleWorkflowService.DeprecateWorkflowType'
    )


class XAmzTarget7(Enum):
    SimpleWorkflowService_DescribeActivityType = (
        'SimpleWorkflowService.DescribeActivityType'
    )


class XAmzTarget8(Enum):
    SimpleWorkflowService_DescribeDomain = 'SimpleWorkflowService.DescribeDomain'


class XAmzTarget9(Enum):
    SimpleWorkflowService_DescribeWorkflowExecution = (
        'SimpleWorkflowService.DescribeWorkflowExecution'
    )


class XAmzTarget10(Enum):
    SimpleWorkflowService_DescribeWorkflowType = (
        'SimpleWorkflowService.DescribeWorkflowType'
    )


class XAmzTarget11(Enum):
    SimpleWorkflowService_GetWorkflowExecutionHistory = (
        'SimpleWorkflowService.GetWorkflowExecutionHistory'
    )


class XAmzTarget12(Enum):
    SimpleWorkflowService_ListActivityTypes = 'SimpleWorkflowService.ListActivityTypes'


class XAmzTarget13(Enum):
    SimpleWorkflowService_ListClosedWorkflowExecutions = (
        'SimpleWorkflowService.ListClosedWorkflowExecutions'
    )


class XAmzTarget14(Enum):
    SimpleWorkflowService_ListDomains = 'SimpleWorkflowService.ListDomains'


class XAmzTarget15(Enum):
    SimpleWorkflowService_ListOpenWorkflowExecutions = (
        'SimpleWorkflowService.ListOpenWorkflowExecutions'
    )


class XAmzTarget16(Enum):
    SimpleWorkflowService_ListTagsForResource = (
        'SimpleWorkflowService.ListTagsForResource'
    )


class XAmzTarget17(Enum):
    SimpleWorkflowService_ListWorkflowTypes = 'SimpleWorkflowService.ListWorkflowTypes'


class XAmzTarget18(Enum):
    SimpleWorkflowService_PollForActivityTask = (
        'SimpleWorkflowService.PollForActivityTask'
    )


class XAmzTarget19(Enum):
    SimpleWorkflowService_PollForDecisionTask = (
        'SimpleWorkflowService.PollForDecisionTask'
    )


class XAmzTarget20(Enum):
    SimpleWorkflowService_RecordActivityTaskHeartbeat = (
        'SimpleWorkflowService.RecordActivityTaskHeartbeat'
    )


class XAmzTarget21(Enum):
    SimpleWorkflowService_RegisterActivityType = (
        'SimpleWorkflowService.RegisterActivityType'
    )


class XAmzTarget22(Enum):
    SimpleWorkflowService_RegisterDomain = 'SimpleWorkflowService.RegisterDomain'


class XAmzTarget23(Enum):
    SimpleWorkflowService_RegisterWorkflowType = (
        'SimpleWorkflowService.RegisterWorkflowType'
    )


class XAmzTarget24(Enum):
    SimpleWorkflowService_RequestCancelWorkflowExecution = (
        'SimpleWorkflowService.RequestCancelWorkflowExecution'
    )


class XAmzTarget25(Enum):
    SimpleWorkflowService_RespondActivityTaskCanceled = (
        'SimpleWorkflowService.RespondActivityTaskCanceled'
    )


class XAmzTarget26(Enum):
    SimpleWorkflowService_RespondActivityTaskCompleted = (
        'SimpleWorkflowService.RespondActivityTaskCompleted'
    )


class XAmzTarget27(Enum):
    SimpleWorkflowService_RespondActivityTaskFailed = (
        'SimpleWorkflowService.RespondActivityTaskFailed'
    )


class XAmzTarget28(Enum):
    SimpleWorkflowService_RespondDecisionTaskCompleted = (
        'SimpleWorkflowService.RespondDecisionTaskCompleted'
    )


class XAmzTarget29(Enum):
    SimpleWorkflowService_SignalWorkflowExecution = (
        'SimpleWorkflowService.SignalWorkflowExecution'
    )


class XAmzTarget30(Enum):
    SimpleWorkflowService_StartWorkflowExecution = (
        'SimpleWorkflowService.StartWorkflowExecution'
    )


class XAmzTarget31(Enum):
    SimpleWorkflowService_TagResource = 'SimpleWorkflowService.TagResource'


class XAmzTarget32(Enum):
    SimpleWorkflowService_TerminateWorkflowExecution = (
        'SimpleWorkflowService.TerminateWorkflowExecution'
    )


class XAmzTarget33(Enum):
    SimpleWorkflowService_UndeprecateActivityType = (
        'SimpleWorkflowService.UndeprecateActivityType'
    )


class XAmzTarget34(Enum):
    SimpleWorkflowService_UndeprecateDomain = 'SimpleWorkflowService.UndeprecateDomain'


class XAmzTarget35(Enum):
    SimpleWorkflowService_UndeprecateWorkflowType = (
        'SimpleWorkflowService.UndeprecateWorkflowType'
    )


class XAmzTarget36(Enum):
    SimpleWorkflowService_UntagResource = 'SimpleWorkflowService.UntagResource'


class ActivityTaskCancelRequestedEventAttributes(BaseModel):
    activityId: ActivityId
    decisionTaskCompletedEventId: EventId


class ActivityTaskCanceledEventAttributes(BaseModel):
    details: Optional[Data] = None
    latestCancelRequestedEventId: Optional[EventId] = None
    scheduledEventId: EventId
    startedEventId: EventId


class ActivityTaskCompletedEventAttributes(BaseModel):
    result: Optional[Data] = None
    scheduledEventId: EventId
    startedEventId: EventId


class ActivityTaskFailedEventAttributes(BaseModel):
    details: Optional[Data] = None
    reason: Optional[FailureReason] = None
    scheduledEventId: EventId
    startedEventId: EventId


class ActivityTaskStartedEventAttributes(BaseModel):
    identity: Optional[Identity] = None
    scheduledEventId: EventId


class ActivityTaskStatus(BaseModel):
    cancelRequested: Canceled


class ActivityTaskTimedOutEventAttributes(BaseModel):
    details: Optional[LimitedData] = None
    scheduledEventId: EventId
    startedEventId: EventId
    timeoutType: ActivityTaskTimeoutType


class ActivityType(BaseModel):
    name: Name
    version: Version


class ActivityTypeConfiguration(BaseModel):
    defaultTaskHeartbeatTimeout: Optional[DurationInSecondsOptional] = None
    defaultTaskList: Optional[TaskList] = None
    defaultTaskPriority: Optional[TaskPriority] = None
    defaultTaskScheduleToCloseTimeout: Optional[DurationInSecondsOptional] = None
    defaultTaskScheduleToStartTimeout: Optional[DurationInSecondsOptional] = None
    defaultTaskStartToCloseTimeout: Optional[DurationInSecondsOptional] = None


class ActivityTypeInfo(BaseModel):
    activityType: ActivityType
    creationDate: Timestamp
    deprecationDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    status: RegistrationStatus


class ActivityTypeInfoList(RootModel[List[ActivityTypeInfo]]):
    root: List[ActivityTypeInfo]


class ActivityTypeInfos(BaseModel):
    nextPageToken: Optional[PageToken] = None
    typeInfos: ActivityTypeInfoList


class CancelTimerDecisionAttributes(BaseModel):
    timerId: TimerId


class CancelTimerFailedEventAttributes(BaseModel):
    cause: CancelTimerFailedCause
    decisionTaskCompletedEventId: EventId
    timerId: TimerId


class CancelWorkflowExecutionDecisionAttributes(BaseModel):
    details: Optional[Data] = None


class CancelWorkflowExecutionFailedEventAttributes(BaseModel):
    cause: CancelWorkflowExecutionFailedCause
    decisionTaskCompletedEventId: EventId


class CompleteWorkflowExecutionDecisionAttributes(BaseModel):
    result: Optional[Data] = None


class CompleteWorkflowExecutionFailedEventAttributes(BaseModel):
    cause: CompleteWorkflowExecutionFailedCause
    decisionTaskCompletedEventId: EventId


class ContinueAsNewWorkflowExecutionDecisionAttributes(BaseModel):
    childPolicy: Optional[ChildPolicy] = None
    executionStartToCloseTimeout: Optional[DurationInSecondsOptional] = None
    input: Optional[Data] = None
    lambdaRole: Optional[Arn] = None
    tagList: Optional[TagList] = None
    taskList: Optional[TaskList] = None
    taskPriority: Optional[TaskPriority] = None
    taskStartToCloseTimeout: Optional[DurationInSecondsOptional] = None
    workflowTypeVersion: Optional[Version] = None


class ContinueAsNewWorkflowExecutionFailedEventAttributes(BaseModel):
    cause: ContinueAsNewWorkflowExecutionFailedCause
    decisionTaskCompletedEventId: EventId


class CountPendingActivityTasksInput(BaseModel):
    domain: DomainName
    taskList: TaskList


class CountPendingDecisionTasksInput(BaseModel):
    domain: DomainName
    taskList: TaskList


class DecisionTaskCompletedEventAttributes(BaseModel):
    executionContext: Optional[Data] = None
    scheduledEventId: EventId
    startedEventId: EventId


class DecisionTaskScheduledEventAttributes(BaseModel):
    startToCloseTimeout: Optional[DurationInSecondsOptional] = None
    taskList: TaskList
    taskPriority: Optional[TaskPriority] = None


class DecisionTaskStartedEventAttributes(BaseModel):
    identity: Optional[Identity] = None
    scheduledEventId: EventId


class DecisionTaskTimedOutEventAttributes(BaseModel):
    scheduledEventId: EventId
    startedEventId: EventId
    timeoutType: DecisionTaskTimeoutType


class DeprecateActivityTypeInput(BaseModel):
    activityType: ActivityType
    domain: DomainName


class DeprecateDomainInput(BaseModel):
    name: DomainName


class DeprecateWorkflowTypeInput(BaseModel):
    domain: DomainName
    workflowType: WorkflowType


class DescribeActivityTypeInput(BaseModel):
    activityType: ActivityType
    domain: DomainName


class DescribeDomainInput(BaseModel):
    name: DomainName


class DescribeWorkflowTypeInput(BaseModel):
    domain: DomainName
    workflowType: WorkflowType


class DomainConfiguration(BaseModel):
    workflowExecutionRetentionPeriodInDays: DurationInDays


class DomainInfo(BaseModel):
    arn: Optional[Arn] = None
    description: Optional[Description] = None
    name: DomainName
    status: RegistrationStatus


class DomainInfoList(RootModel[List[DomainInfo]]):
    root: List[DomainInfo]


class DomainInfos(BaseModel):
    domainInfos: DomainInfoList
    nextPageToken: Optional[PageToken] = None


class ExecutionTimeFilter(BaseModel):
    latestDate: Optional[Timestamp] = None
    oldestDate: Timestamp


class FailWorkflowExecutionDecisionAttributes(BaseModel):
    details: Optional[Data] = None
    reason: Optional[FailureReason] = None


class LambdaFunctionTimedOutEventAttributes(BaseModel):
    scheduledEventId: EventId
    startedEventId: EventId
    timeoutType: Optional[LambdaFunctionTimeoutType] = None


class ListActivityTypesInput(BaseModel):
    domain: DomainName
    maximumPageSize: Optional[PageSize] = None
    name: Optional[Name] = None
    nextPageToken: Optional[PageToken] = None
    registrationStatus: RegistrationStatus
    reverseOrder: Optional[ReverseOrder] = None


class ListDomainsInput(BaseModel):
    maximumPageSize: Optional[PageSize] = None
    nextPageToken: Optional[PageToken] = None
    registrationStatus: RegistrationStatus
    reverseOrder: Optional[ReverseOrder] = None


class ListWorkflowTypesInput(BaseModel):
    domain: DomainName
    maximumPageSize: Optional[PageSize] = None
    name: Optional[Name] = None
    nextPageToken: Optional[PageToken] = None
    registrationStatus: RegistrationStatus
    reverseOrder: Optional[ReverseOrder] = None


class PendingTaskCount(BaseModel):
    count: Count
    truncated: Optional[Truncated] = None


class PollForActivityTaskInput(BaseModel):
    domain: DomainName
    identity: Optional[Identity] = None
    taskList: TaskList


class PollForDecisionTaskInput(BaseModel):
    domain: DomainName
    identity: Optional[Identity] = None
    maximumPageSize: Optional[PageSize] = None
    nextPageToken: Optional[PageToken] = None
    reverseOrder: Optional[ReverseOrder] = None
    taskList: TaskList


class RecordActivityTaskHeartbeatInput(BaseModel):
    details: Optional[LimitedData] = None
    taskToken: TaskToken


class RegisterActivityTypeInput(BaseModel):
    defaultTaskHeartbeatTimeout: Optional[DurationInSecondsOptional] = None
    defaultTaskList: Optional[TaskList] = None
    defaultTaskPriority: Optional[TaskPriority] = None
    defaultTaskScheduleToCloseTimeout: Optional[DurationInSecondsOptional] = None
    defaultTaskScheduleToStartTimeout: Optional[DurationInSecondsOptional] = None
    defaultTaskStartToCloseTimeout: Optional[DurationInSecondsOptional] = None
    description: Optional[Description] = None
    domain: DomainName
    name: Name
    version: Version


class RegisterWorkflowTypeInput(BaseModel):
    defaultChildPolicy: Optional[ChildPolicy] = None
    defaultExecutionStartToCloseTimeout: Optional[DurationInSecondsOptional] = None
    defaultLambdaRole: Optional[Arn] = None
    defaultTaskList: Optional[TaskList] = None
    defaultTaskPriority: Optional[TaskPriority] = None
    defaultTaskStartToCloseTimeout: Optional[DurationInSecondsOptional] = None
    description: Optional[Description] = None
    domain: DomainName
    name: Name
    version: Version


class RequestCancelExternalWorkflowExecutionDecisionAttributes(BaseModel):
    control: Optional[Data] = None
    runId: Optional[WorkflowRunIdOptional] = None
    workflowId: WorkflowId


class RequestCancelExternalWorkflowExecutionFailedEventAttributes(BaseModel):
    cause: RequestCancelExternalWorkflowExecutionFailedCause
    control: Optional[Data] = None
    decisionTaskCompletedEventId: EventId
    initiatedEventId: EventId
    runId: Optional[WorkflowRunIdOptional] = None
    workflowId: WorkflowId


class RequestCancelExternalWorkflowExecutionInitiatedEventAttributes(BaseModel):
    control: Optional[Data] = None
    decisionTaskCompletedEventId: EventId
    runId: Optional[WorkflowRunIdOptional] = None
    workflowId: WorkflowId


class RequestCancelWorkflowExecutionInput(BaseModel):
    domain: DomainName
    runId: Optional[WorkflowRunIdOptional] = None
    workflowId: WorkflowId


class ResourceTag(BaseModel):
    key: ResourceTagKey
    value: Optional[ResourceTagValue] = None


class ResourceTagList(RootModel[List[ResourceTag]]):
    root: List[ResourceTag]


class RespondActivityTaskCanceledInput(BaseModel):
    details: Optional[Data] = None
    taskToken: TaskToken


class RespondActivityTaskCompletedInput(BaseModel):
    result: Optional[Data] = None
    taskToken: TaskToken


class RespondActivityTaskFailedInput(BaseModel):
    details: Optional[Data] = None
    reason: Optional[FailureReason] = None
    taskToken: TaskToken


class Run(BaseModel):
    runId: Optional[WorkflowRunId] = None


class ScheduleActivityTaskDecisionAttributes(BaseModel):
    activityId: ActivityId
    activityType: ActivityType
    control: Optional[Data] = None
    heartbeatTimeout: Optional[DurationInSecondsOptional] = None
    input: Optional[Data] = None
    scheduleToCloseTimeout: Optional[DurationInSecondsOptional] = None
    scheduleToStartTimeout: Optional[DurationInSecondsOptional] = None
    startToCloseTimeout: Optional[DurationInSecondsOptional] = None
    taskList: Optional[TaskList] = None
    taskPriority: Optional[TaskPriority] = None


class ScheduleActivityTaskFailedEventAttributes(BaseModel):
    activityId: ActivityId
    activityType: ActivityType
    cause: ScheduleActivityTaskFailedCause
    decisionTaskCompletedEventId: EventId


class SignalExternalWorkflowExecutionDecisionAttributes(BaseModel):
    control: Optional[Data] = None
    input: Optional[Data] = None
    runId: Optional[WorkflowRunIdOptional] = None
    signalName: SignalName
    workflowId: WorkflowId


class SignalExternalWorkflowExecutionFailedEventAttributes(BaseModel):
    cause: SignalExternalWorkflowExecutionFailedCause
    control: Optional[Data] = None
    decisionTaskCompletedEventId: EventId
    initiatedEventId: EventId
    runId: Optional[WorkflowRunIdOptional] = None
    workflowId: WorkflowId


class SignalExternalWorkflowExecutionInitiatedEventAttributes(BaseModel):
    control: Optional[Data] = None
    decisionTaskCompletedEventId: EventId
    input: Optional[Data] = None
    runId: Optional[WorkflowRunIdOptional] = None
    signalName: SignalName
    workflowId: WorkflowId


class SignalWorkflowExecutionInput(BaseModel):
    domain: DomainName
    input: Optional[Data] = None
    runId: Optional[WorkflowRunIdOptional] = None
    signalName: SignalName
    workflowId: WorkflowId


class StartChildWorkflowExecutionDecisionAttributes(BaseModel):
    childPolicy: Optional[ChildPolicy] = None
    control: Optional[Data] = None
    executionStartToCloseTimeout: Optional[DurationInSecondsOptional] = None
    input: Optional[Data] = None
    lambdaRole: Optional[Arn] = None
    tagList: Optional[TagList] = None
    taskList: Optional[TaskList] = None
    taskPriority: Optional[TaskPriority] = None
    taskStartToCloseTimeout: Optional[DurationInSecondsOptional] = None
    workflowId: WorkflowId
    workflowType: WorkflowType


class StartChildWorkflowExecutionFailedEventAttributes(BaseModel):
    cause: StartChildWorkflowExecutionFailedCause
    control: Optional[Data] = None
    decisionTaskCompletedEventId: EventId
    initiatedEventId: EventId
    workflowId: WorkflowId
    workflowType: WorkflowType


class StartChildWorkflowExecutionInitiatedEventAttributes(BaseModel):
    childPolicy: ChildPolicy
    control: Optional[Data] = None
    decisionTaskCompletedEventId: EventId
    executionStartToCloseTimeout: Optional[DurationInSecondsOptional] = None
    input: Optional[Data] = None
    lambdaRole: Optional[Arn] = None
    tagList: Optional[TagList] = None
    taskList: TaskList
    taskPriority: Optional[TaskPriority] = None
    taskStartToCloseTimeout: Optional[DurationInSecondsOptional] = None
    workflowId: WorkflowId
    workflowType: WorkflowType


class StartTimerDecisionAttributes(BaseModel):
    control: Optional[Data] = None
    startToFireTimeout: DurationInSeconds
    timerId: TimerId


class StartTimerFailedEventAttributes(BaseModel):
    cause: StartTimerFailedCause
    decisionTaskCompletedEventId: EventId
    timerId: TimerId


class StartWorkflowExecutionInput(BaseModel):
    childPolicy: Optional[ChildPolicy] = None
    domain: DomainName
    executionStartToCloseTimeout: Optional[DurationInSecondsOptional] = None
    input: Optional[Data] = None
    lambdaRole: Optional[Arn] = None
    tagList: Optional[TagList] = None
    taskList: Optional[TaskList] = None
    taskPriority: Optional[TaskPriority] = None
    taskStartToCloseTimeout: Optional[DurationInSecondsOptional] = None
    workflowId: WorkflowId
    workflowType: WorkflowType


class TagResourceInput(BaseModel):
    resourceArn: Arn
    tags: ResourceTagList


class TerminateWorkflowExecutionInput(BaseModel):
    childPolicy: Optional[ChildPolicy] = None
    details: Optional[Data] = None
    domain: DomainName
    reason: Optional[TerminateReason] = None
    runId: Optional[WorkflowRunIdOptional] = None
    workflowId: WorkflowId


class TimerCanceledEventAttributes(BaseModel):
    decisionTaskCompletedEventId: EventId
    startedEventId: EventId
    timerId: TimerId


class TimerFiredEventAttributes(BaseModel):
    startedEventId: EventId
    timerId: TimerId


class UndeprecateActivityTypeInput(BaseModel):
    activityType: ActivityType
    domain: DomainName


class UndeprecateWorkflowTypeInput(BaseModel):
    domain: DomainName
    workflowType: WorkflowType


class WorkflowExecution(BaseModel):
    runId: WorkflowRunId
    workflowId: WorkflowId


class WorkflowExecutionCancelRequestedEventAttributes(BaseModel):
    cause: Optional[WorkflowExecutionCancelRequestedCause] = None
    externalInitiatedEventId: Optional[EventId] = None
    externalWorkflowExecution: Optional[WorkflowExecution] = None


class WorkflowExecutionContinuedAsNewEventAttributes(BaseModel):
    childPolicy: ChildPolicy
    decisionTaskCompletedEventId: EventId
    executionStartToCloseTimeout: Optional[DurationInSecondsOptional] = None
    input: Optional[Data] = None
    lambdaRole: Optional[Arn] = None
    newExecutionRunId: WorkflowRunId
    tagList: Optional[TagList] = None
    taskList: TaskList
    taskPriority: Optional[TaskPriority] = None
    taskStartToCloseTimeout: Optional[DurationInSecondsOptional] = None
    workflowType: WorkflowType


class WorkflowExecutionFilter(BaseModel):
    workflowId: WorkflowId


class WorkflowExecutionInfo(BaseModel):
    cancelRequested: Optional[Canceled] = None
    closeStatus: Optional[CloseStatus] = None
    closeTimestamp: Optional[Timestamp] = None
    execution: WorkflowExecution
    executionStatus: ExecutionStatus
    parent: Optional[WorkflowExecution] = None
    startTimestamp: Timestamp
    tagList: Optional[TagList] = None
    workflowType: WorkflowType


class WorkflowExecutionInfoList(RootModel[List[WorkflowExecutionInfo]]):
    root: List[WorkflowExecutionInfo]


class WorkflowExecutionInfos(BaseModel):
    executionInfos: WorkflowExecutionInfoList
    nextPageToken: Optional[PageToken] = None


class WorkflowExecutionSignaledEventAttributes(BaseModel):
    externalInitiatedEventId: Optional[EventId] = None
    externalWorkflowExecution: Optional[WorkflowExecution] = None
    input: Optional[Data] = None
    signalName: SignalName


class WorkflowExecutionStartedEventAttributes(BaseModel):
    childPolicy: ChildPolicy
    continuedExecutionRunId: Optional[WorkflowRunIdOptional] = None
    executionStartToCloseTimeout: Optional[DurationInSecondsOptional] = None
    input: Optional[Data] = None
    lambdaRole: Optional[Arn] = None
    parentInitiatedEventId: Optional[EventId] = None
    parentWorkflowExecution: Optional[WorkflowExecution] = None
    tagList: Optional[TagList] = None
    taskList: TaskList
    taskPriority: Optional[TaskPriority] = None
    taskStartToCloseTimeout: Optional[DurationInSecondsOptional] = None
    workflowType: WorkflowType


class WorkflowExecutionTimedOutEventAttributes(BaseModel):
    childPolicy: ChildPolicy
    timeoutType: WorkflowExecutionTimeoutType


class WorkflowTypeDetail(BaseModel):
    configuration: WorkflowTypeConfiguration
    typeInfo: WorkflowTypeInfo


class ActivityTask(BaseModel):
    activityId: ActivityId
    activityType: ActivityType
    input: Optional[Data] = None
    startedEventId: EventId
    taskToken: TaskToken
    workflowExecution: WorkflowExecution


class ActivityTaskScheduledEventAttributes(BaseModel):
    activityId: ActivityId
    activityType: ActivityType
    control: Optional[Data] = None
    decisionTaskCompletedEventId: EventId
    heartbeatTimeout: Optional[DurationInSecondsOptional] = None
    input: Optional[Data] = None
    scheduleToCloseTimeout: Optional[DurationInSecondsOptional] = None
    scheduleToStartTimeout: Optional[DurationInSecondsOptional] = None
    startToCloseTimeout: Optional[DurationInSecondsOptional] = None
    taskList: TaskList
    taskPriority: Optional[TaskPriority] = None


class ActivityTypeDetail(BaseModel):
    configuration: ActivityTypeConfiguration
    typeInfo: ActivityTypeInfo


class ChildWorkflowExecutionCanceledEventAttributes(BaseModel):
    details: Optional[Data] = None
    initiatedEventId: EventId
    startedEventId: EventId
    workflowExecution: WorkflowExecution
    workflowType: WorkflowType


class ChildWorkflowExecutionCompletedEventAttributes(BaseModel):
    initiatedEventId: EventId
    result: Optional[Data] = None
    startedEventId: EventId
    workflowExecution: WorkflowExecution
    workflowType: WorkflowType


class ChildWorkflowExecutionFailedEventAttributes(BaseModel):
    details: Optional[Data] = None
    initiatedEventId: EventId
    reason: Optional[FailureReason] = None
    startedEventId: EventId
    workflowExecution: WorkflowExecution
    workflowType: WorkflowType


class ChildWorkflowExecutionStartedEventAttributes(BaseModel):
    initiatedEventId: EventId
    workflowExecution: WorkflowExecution
    workflowType: WorkflowType


class ChildWorkflowExecutionTerminatedEventAttributes(BaseModel):
    initiatedEventId: EventId
    startedEventId: EventId
    workflowExecution: WorkflowExecution
    workflowType: WorkflowType


class ChildWorkflowExecutionTimedOutEventAttributes(BaseModel):
    initiatedEventId: EventId
    startedEventId: EventId
    timeoutType: WorkflowExecutionTimeoutType
    workflowExecution: WorkflowExecution
    workflowType: WorkflowType


class CountClosedWorkflowExecutionsInput(BaseModel):
    closeStatusFilter: Optional[CloseStatusFilter] = None
    closeTimeFilter: Optional[ExecutionTimeFilter] = None
    domain: DomainName
    executionFilter: Optional[WorkflowExecutionFilter] = None
    startTimeFilter: Optional[ExecutionTimeFilter] = None
    tagFilter: Optional[TagFilter] = None
    typeFilter: Optional[WorkflowTypeFilter] = None


class CountOpenWorkflowExecutionsInput(BaseModel):
    domain: DomainName
    executionFilter: Optional[WorkflowExecutionFilter] = None
    startTimeFilter: ExecutionTimeFilter
    tagFilter: Optional[TagFilter] = None
    typeFilter: Optional[WorkflowTypeFilter] = None


class Decision(BaseModel):
    cancelTimerDecisionAttributes: Optional[CancelTimerDecisionAttributes] = None
    cancelWorkflowExecutionDecisionAttributes: Optional[
        CancelWorkflowExecutionDecisionAttributes
    ] = None
    completeWorkflowExecutionDecisionAttributes: Optional[
        CompleteWorkflowExecutionDecisionAttributes
    ] = None
    continueAsNewWorkflowExecutionDecisionAttributes: Optional[
        ContinueAsNewWorkflowExecutionDecisionAttributes
    ] = None
    decisionType: DecisionType
    failWorkflowExecutionDecisionAttributes: Optional[
        FailWorkflowExecutionDecisionAttributes
    ] = None
    recordMarkerDecisionAttributes: Optional[RecordMarkerDecisionAttributes] = None
    requestCancelActivityTaskDecisionAttributes: Optional[
        RequestCancelActivityTaskDecisionAttributes
    ] = None
    requestCancelExternalWorkflowExecutionDecisionAttributes: Optional[
        RequestCancelExternalWorkflowExecutionDecisionAttributes
    ] = None
    scheduleActivityTaskDecisionAttributes: Optional[
        ScheduleActivityTaskDecisionAttributes
    ] = None
    scheduleLambdaFunctionDecisionAttributes: Optional[
        ScheduleLambdaFunctionDecisionAttributes
    ] = None
    signalExternalWorkflowExecutionDecisionAttributes: Optional[
        SignalExternalWorkflowExecutionDecisionAttributes
    ] = None
    startChildWorkflowExecutionDecisionAttributes: Optional[
        StartChildWorkflowExecutionDecisionAttributes
    ] = None
    startTimerDecisionAttributes: Optional[StartTimerDecisionAttributes] = None


class DecisionList(RootModel[List[Decision]]):
    root: List[Decision]


class DescribeWorkflowExecutionInput(BaseModel):
    domain: DomainName
    execution: WorkflowExecution


class DomainDetail(BaseModel):
    configuration: DomainConfiguration
    domainInfo: DomainInfo


class ExternalWorkflowExecutionCancelRequestedEventAttributes(BaseModel):
    initiatedEventId: EventId
    workflowExecution: WorkflowExecution


class ExternalWorkflowExecutionSignaledEventAttributes(BaseModel):
    initiatedEventId: EventId
    workflowExecution: WorkflowExecution


class GetWorkflowExecutionHistoryInput(BaseModel):
    domain: DomainName
    execution: WorkflowExecution
    maximumPageSize: Optional[PageSize] = None
    nextPageToken: Optional[PageToken] = None
    reverseOrder: Optional[ReverseOrder] = None


class HistoryEvent(BaseModel):
    activityTaskCancelRequestedEventAttributes: Optional[
        ActivityTaskCancelRequestedEventAttributes
    ] = None
    activityTaskCanceledEventAttributes: Optional[
        ActivityTaskCanceledEventAttributes
    ] = None
    activityTaskCompletedEventAttributes: Optional[
        ActivityTaskCompletedEventAttributes
    ] = None
    activityTaskFailedEventAttributes: Optional[ActivityTaskFailedEventAttributes] = (
        None
    )
    activityTaskScheduledEventAttributes: Optional[
        ActivityTaskScheduledEventAttributes
    ] = None
    activityTaskStartedEventAttributes: Optional[ActivityTaskStartedEventAttributes] = (
        None
    )
    activityTaskTimedOutEventAttributes: Optional[
        ActivityTaskTimedOutEventAttributes
    ] = None
    cancelTimerFailedEventAttributes: Optional[CancelTimerFailedEventAttributes] = None
    cancelWorkflowExecutionFailedEventAttributes: Optional[
        CancelWorkflowExecutionFailedEventAttributes
    ] = None
    childWorkflowExecutionCanceledEventAttributes: Optional[
        ChildWorkflowExecutionCanceledEventAttributes
    ] = None
    childWorkflowExecutionCompletedEventAttributes: Optional[
        ChildWorkflowExecutionCompletedEventAttributes
    ] = None
    childWorkflowExecutionFailedEventAttributes: Optional[
        ChildWorkflowExecutionFailedEventAttributes
    ] = None
    childWorkflowExecutionStartedEventAttributes: Optional[
        ChildWorkflowExecutionStartedEventAttributes
    ] = None
    childWorkflowExecutionTerminatedEventAttributes: Optional[
        ChildWorkflowExecutionTerminatedEventAttributes
    ] = None
    childWorkflowExecutionTimedOutEventAttributes: Optional[
        ChildWorkflowExecutionTimedOutEventAttributes
    ] = None
    completeWorkflowExecutionFailedEventAttributes: Optional[
        CompleteWorkflowExecutionFailedEventAttributes
    ] = None
    continueAsNewWorkflowExecutionFailedEventAttributes: Optional[
        ContinueAsNewWorkflowExecutionFailedEventAttributes
    ] = None
    decisionTaskCompletedEventAttributes: Optional[
        DecisionTaskCompletedEventAttributes
    ] = None
    decisionTaskScheduledEventAttributes: Optional[
        DecisionTaskScheduledEventAttributes
    ] = None
    decisionTaskStartedEventAttributes: Optional[DecisionTaskStartedEventAttributes] = (
        None
    )
    decisionTaskTimedOutEventAttributes: Optional[
        DecisionTaskTimedOutEventAttributes
    ] = None
    eventId: EventId
    eventTimestamp: Timestamp
    eventType: EventType
    externalWorkflowExecutionCancelRequestedEventAttributes: Optional[
        ExternalWorkflowExecutionCancelRequestedEventAttributes
    ] = None
    externalWorkflowExecutionSignaledEventAttributes: Optional[
        ExternalWorkflowExecutionSignaledEventAttributes
    ] = None
    failWorkflowExecutionFailedEventAttributes: Optional[
        FailWorkflowExecutionFailedEventAttributes
    ] = None
    lambdaFunctionCompletedEventAttributes: Optional[
        LambdaFunctionCompletedEventAttributes
    ] = None
    lambdaFunctionFailedEventAttributes: Optional[
        LambdaFunctionFailedEventAttributes
    ] = None
    lambdaFunctionScheduledEventAttributes: Optional[
        LambdaFunctionScheduledEventAttributes
    ] = None
    lambdaFunctionStartedEventAttributes: Optional[
        LambdaFunctionStartedEventAttributes
    ] = None
    lambdaFunctionTimedOutEventAttributes: Optional[
        LambdaFunctionTimedOutEventAttributes
    ] = None
    markerRecordedEventAttributes: Optional[MarkerRecordedEventAttributes] = None
    recordMarkerFailedEventAttributes: Optional[RecordMarkerFailedEventAttributes] = (
        None
    )
    requestCancelActivityTaskFailedEventAttributes: Optional[
        RequestCancelActivityTaskFailedEventAttributes
    ] = None
    requestCancelExternalWorkflowExecutionFailedEventAttributes: Optional[
        RequestCancelExternalWorkflowExecutionFailedEventAttributes
    ] = None
    requestCancelExternalWorkflowExecutionInitiatedEventAttributes: Optional[
        RequestCancelExternalWorkflowExecutionInitiatedEventAttributes
    ] = None
    scheduleActivityTaskFailedEventAttributes: Optional[
        ScheduleActivityTaskFailedEventAttributes
    ] = None
    scheduleLambdaFunctionFailedEventAttributes: Optional[
        ScheduleLambdaFunctionFailedEventAttributes
    ] = None
    signalExternalWorkflowExecutionFailedEventAttributes: Optional[
        SignalExternalWorkflowExecutionFailedEventAttributes
    ] = None
    signalExternalWorkflowExecutionInitiatedEventAttributes: Optional[
        SignalExternalWorkflowExecutionInitiatedEventAttributes
    ] = None
    startChildWorkflowExecutionFailedEventAttributes: Optional[
        StartChildWorkflowExecutionFailedEventAttributes
    ] = None
    startChildWorkflowExecutionInitiatedEventAttributes: Optional[
        StartChildWorkflowExecutionInitiatedEventAttributes
    ] = None
    startLambdaFunctionFailedEventAttributes: Optional[
        StartLambdaFunctionFailedEventAttributes
    ] = None
    startTimerFailedEventAttributes: Optional[StartTimerFailedEventAttributes] = None
    timerCanceledEventAttributes: Optional[TimerCanceledEventAttributes] = None
    timerFiredEventAttributes: Optional[TimerFiredEventAttributes] = None
    timerStartedEventAttributes: Optional[TimerStartedEventAttributes] = None
    workflowExecutionCancelRequestedEventAttributes: Optional[
        WorkflowExecutionCancelRequestedEventAttributes
    ] = None
    workflowExecutionCanceledEventAttributes: Optional[
        WorkflowExecutionCanceledEventAttributes
    ] = None
    workflowExecutionCompletedEventAttributes: Optional[
        WorkflowExecutionCompletedEventAttributes
    ] = None
    workflowExecutionContinuedAsNewEventAttributes: Optional[
        WorkflowExecutionContinuedAsNewEventAttributes
    ] = None
    workflowExecutionFailedEventAttributes: Optional[
        WorkflowExecutionFailedEventAttributes
    ] = None
    workflowExecutionSignaledEventAttributes: Optional[
        WorkflowExecutionSignaledEventAttributes
    ] = None
    workflowExecutionStartedEventAttributes: Optional[
        WorkflowExecutionStartedEventAttributes
    ] = None
    workflowExecutionTerminatedEventAttributes: Optional[
        WorkflowExecutionTerminatedEventAttributes
    ] = None
    workflowExecutionTimedOutEventAttributes: Optional[
        WorkflowExecutionTimedOutEventAttributes
    ] = None


class HistoryEventList(RootModel[List[HistoryEvent]]):
    root: List[HistoryEvent]


class ListClosedWorkflowExecutionsInput(BaseModel):
    closeStatusFilter: Optional[CloseStatusFilter] = None
    closeTimeFilter: Optional[ExecutionTimeFilter] = None
    domain: DomainName
    executionFilter: Optional[WorkflowExecutionFilter] = None
    maximumPageSize: Optional[PageSize] = None
    nextPageToken: Optional[PageToken] = None
    reverseOrder: Optional[ReverseOrder] = None
    startTimeFilter: Optional[ExecutionTimeFilter] = None
    tagFilter: Optional[TagFilter] = None
    typeFilter: Optional[WorkflowTypeFilter] = None


class ListOpenWorkflowExecutionsInput(BaseModel):
    domain: DomainName
    executionFilter: Optional[WorkflowExecutionFilter] = None
    maximumPageSize: Optional[PageSize] = None
    nextPageToken: Optional[PageToken] = None
    reverseOrder: Optional[ReverseOrder] = None
    startTimeFilter: ExecutionTimeFilter
    tagFilter: Optional[TagFilter] = None
    typeFilter: Optional[WorkflowTypeFilter] = None


class ListTagsForResourceOutput(BaseModel):
    tags: Optional[ResourceTagList] = None


class RegisterDomainInput(BaseModel):
    description: Optional[Description] = None
    name: DomainName
    tags: Optional[ResourceTagList] = None
    workflowExecutionRetentionPeriodInDays: DurationInDays


class RespondDecisionTaskCompletedInput(BaseModel):
    decisions: Optional[DecisionList] = None
    executionContext: Optional[Data] = None
    taskToken: TaskToken


class WorkflowExecutionDetail(BaseModel):
    executionConfiguration: WorkflowExecutionConfiguration
    executionInfo: WorkflowExecutionInfo
    latestActivityTaskTimestamp: Optional[Timestamp] = None
    latestExecutionContext: Optional[Data] = None
    openCounts: WorkflowExecutionOpenCounts


class DecisionTask(BaseModel):
    events: HistoryEventList
    nextPageToken: Optional[PageToken] = None
    previousStartedEventId: Optional[EventId] = None
    startedEventId: EventId
    taskToken: TaskToken
    workflowExecution: WorkflowExecution
    workflowType: WorkflowType


class History(BaseModel):
    events: HistoryEventList
    nextPageToken: Optional[PageToken] = None
